# config/packages/liip_imagine.yamn

liip_imagine:
#    driver: imagick
    driver: gd
    twig:
        mode: lazy
    default_filter_set_settings:
        format: webp
        quality: 68

    loaders:
        flysystem_loader:
            flysystem:
                # this comes from flysystem.yaml
                filesystem_service: local.storage

    # default loader to use for all filter sets
    data_loader: flysystem_loader
    filter_sets:
        auto_rotate: ~
#        large:
#            filters:
#                thumbnail:
#                    size:          [1280, 1280]
#                    allow_upscale: true
#                    mode: inset
        medium:
            filters:
                thumbnail:
                    size:          [512, 512]
                    allow_upscale: true
                    mode: inset

        small:
            filters:
                thumbnail:
                    size:          [192, 192]
#                    allow_upscale: true
                    mode: inset


    controller:
        filter_action:        'App\Controller\ImageController::filterAction'
        filter_runtime_action:        'App\Controller\ImageController::filterRuntimeAction'
        redirect_response_code: 302
