# Default configuration for extension with alias: "survos_media"
survos_media:
    default_locale:       en
    cache_ttl:            3600
    sais_integration:     true
    imgproxy:
        base_url:             'https://imgproxy.survos.com'
        key:                  '%env(IMGPROXY_KEY)%'
        salt:                 '%env(IMGPROXY_SALT)%'
    media_server:
        host:                 'https://media.wip'
        apiKey:               null
        resize_path:          '/media/{preset}/{id}'
    presets:

        # Prototype
        name:
            resize:               fit
            width:                ~ # Required
            height:               ~ # Required
    providers:

        # Prototype
        name:
            enabled:              true
            api_key:              ~
            api_secret:           ~
            access_token:         ~
            options:              []

