services:
#  imgproxy:
#    image: docker.io/darthsim/imgproxy:latest
#    container_name: imgproxy
#    ports:
#      - "9005:8080"
#    environment:
#      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/images
#      - IMGPROXY_ALLOW_ORIGIN=*
#    volumes:
#      - ./data/images:/images
#    restart: unless-stopped

  tesseract:
    image: docker.io/hertzg/tesseract-server:latest
    container_name: tesseract
    ports:
      - "8884:8884"
    restart: unless-stopped

#  ollama:
#    image: docker.io/ollama/ollama:latest
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./data/ollama:/root/.ollama
#    restart: unless-stopped

  opencv:
    build:
      context: .
      dockerfile: Dockerfile.opencv
    container_name: opencv
    ports:
      - "8885:8885"
    volumes:
      - ./data/images:/images
    restart: unless-stopped

